variables:
  IMAGE_NAME: mkdocs-image
  DOCKER_TLS_CERTDIR: ""


stages:
  - docker-prepare
  - deploy

pages:
  image: docker.io/peek1e/mkdocs-image
  stage: deploy
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main

docker-build:
  image: docker
  services:
    - docker:dind
  stage: docker-prepare
  script:
    - echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
    - docker build -t docker.io/$DOCKER_USER/$IMAGE_NAME .
    - docker push docker.io/$DOCKER_USER/$IMAGE_NAME
  only:
    refs:
      - main
    changes:
      - Dockerfile
    
