image: docker.io/peek1e/mkdocs-image

services:
  - docker:dind

stages:
  - deploy

pages:
  stage: deploy
  script:
    - cp . .
    - mkdocks build
  artifacts:
    paths:
      - site
  only:
    - main
